// Code generated by MockGen. DO NOT EDIT.
// Source: azappconfig/provider/internal/loader (interfaces: ConfigClientManager)

// Package mocks is a generated GoMock package.
package mocks

import (
	v1 "azappconfig/provider/api/v1"
	loader "azappconfig/provider/internal/loader"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfigClientManager is a mock of ConfigClientManager interface.
type MockConfigClientManager struct {
	ctrl     *gomock.Controller
	recorder *MockConfigClientManagerMockRecorder
}

// MockConfigClientManagerMockRecorder is the mock recorder for MockConfigClientManager.
type MockConfigClientManagerMockRecorder struct {
	mock *MockConfigClientManager
}

// NewMockConfigClientManager creates a new mock instance.
func NewMockConfigClientManager(ctrl *gomock.Controller) *MockConfigClientManager {
	mock := &MockConfigClientManager{ctrl: ctrl}
	mock.recorder = &MockConfigClientManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigClientManager) EXPECT() *MockConfigClientManagerMockRecorder {
	return m.recorder
}

// DiscoverFallbackClients mocks base method.
func (m *MockConfigClientManager) DiscoverFallbackClients(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverFallbackClients", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DiscoverFallbackClients indicates an expected call of DiscoverFallbackClients.
func (mr *MockConfigClientManagerMockRecorder) DiscoverFallbackClients(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverFallbackClients", reflect.TypeOf((*MockConfigClientManager)(nil).DiscoverFallbackClients), arg0)
}

// GetClients mocks base method.
func (m *MockConfigClientManager) GetClients() []*loader.ConfigurationClientWrapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClients")
	ret0, _ := ret[0].([]*loader.ConfigurationClientWrapper)
	return ret0
}

// GetClients indicates an expected call of GetClients.
func (mr *MockConfigClientManagerMockRecorder) GetClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClients", reflect.TypeOf((*MockConfigClientManager)(nil).GetClients))
}

// NewConfigurationClientManager mocks base method.
func (m *MockConfigClientManager) NewConfigurationClientManager(arg0 context.Context, arg1 v1.AzureAppConfigurationProvider) (*loader.ConfigurationClientManager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConfigurationClientManager", arg0, arg1)
	ret0, _ := ret[0].(*loader.ConfigurationClientManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConfigurationClientManager indicates an expected call of NewConfigurationClientManager.
func (mr *MockConfigClientManagerMockRecorder) NewConfigurationClientManager(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConfigurationClientManager", reflect.TypeOf((*MockConfigClientManager)(nil).NewConfigurationClientManager), arg0, arg1)
}
