name: AppConfiguration-KubernetesProvider CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Run Build
      run: go build -o ./out/manager ./cmd/main.go
    - name: Run Test
      run:  |
        echo 'Install evntest tool'
        GOBIN=${{github.workspace}} go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
        echo 'List files in GOBIN'
        ls -l $GOBIN
        echo 'Run tests'
        KUBEBUILDER_ASSETS=$($GOBIN/setup-envtest use 1.19 -p path) CGO_ENABLED=0 go test ./... -coverprofile cover.out
        ls -l $KUBEBUILDER_ASSETS  